sudo: required
dist: 
  - precise
  - trusty

compiler:
  - clang
  - gcc

env:
  global:
  # encrypted COVERITY_SCAN_TOKEN
  - secure: "HaAhA0LDTyoLYw3JEdVUCrMJW9jWXqdSkoNrc5yeT1qVhC2s+qXjtAXmns4pkxm8NjzQsdlr1qG7QS6kKg/Ea0JUBQx4EbEkFXu2X65+ed2qMZjj57aHIF54BuVRyw/vE5Ogh5W6rK0K4NyFLD+4EdUXcJr+nLUV4wB283roO6sQMqH2RJRgpYlo91sUAigQefSJoRtELqRWil5JtQnN0MLMGiaCTJIHdRWMvBYkw8+xj1QCLw+JJ6f0D012svYiVwWsDfzR8aSpzIhjpFDPEly7ABNPipLw1o57Gi0NwKRlsN2//hNQHMt+C3SMse7sP3PVqlSJrE/n/ofRf3U95cby5XMVgwxmmmbwbCSO8wlEgu1ulYoE2gbCnDBDSz56UeLeTaP9x9mtRyR89B5C2oTvz8qiTII05GDe2qCWsIWqarwNg00XaEfjIbd+Rom9gSRjf0tC72vfleJb0U1TLk2DJxPLPj1yifkliaD1MOF1ekC/a3E/MuXQsB7ZPwVhIe1B7+tw3a9Vsfg6m3PALV/DW+s14KH4e8AlvILIYhr2N44D0zNVh+EPguwCtGynqORF7lgl/9AcJtt53zYN9PAXGnoM3K6dHwzLThE3WcTfM3agWNG33bM4ExHy8FzuGH+Z9IygXO/xey+1iWsil5BTG6CekVceguqPBGJ73Hg="

addons:
  coverity_scan:
    project:
      name: "shartge/pam_setquota"
      description: "PAM module for setting disk quotas on login"
    notification_email: sven@svenhartge.de
    build_command: "make"
    branch_pattern: coverity_scan

  apt:
    packages:
    - build-essential
    - clang-format-3.4
    - linux-libc-dev
    - libpam0g-dev

git:
  depth: 3

script: ./test.sh
